[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false
seeds = true

[programs.localnet]
first_anchor_program = "Cs18SRUb2BypNtWtRxMnVMymMEFJyJoscy3bMJfv3jPQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "my_wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
